# Generated by Django 3.0.5 on 2021-06-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='file_in_binary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
